name: OzempicAI

options:
  bundleIdPrefix: com.mihirpatel
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.0"

packages:
  Supabase:
    url: https://github.com/supabase/supabase-swift
    from: "2.0.0"

targets:
  OzempicAI:
    type: application
    platform: iOS
    sources:
      - path: OzempicAI
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.mihirpatel.OzempicAI
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "5.9"
        INFOPLIST_FILE: OzempicAI/App/Info.plist
        DEVELOPMENT_TEAM: ""
    dependencies:
      - package: Supabase
        product: Supabase
    entitlements:
      path: OzempicAI/App/OzempicAI.entitlements
      properties:
        com.apple.developer.healthkit: true
        com.apple.developer.healthkit.access: []
